### ISSUE TITLE
help ( exagear apk edit )

### ISSUE THREAD

**Issue by saman-aliveisi** [ewt45/ewt45.github.io#1]
Hello dear friend, nice to meet you.
I want to edit the apk related to exagear, for example, add a button to an activity in exagear and create a new apk file.
But I don't know how to do this.
I would be very grateful if you could provide me with a video or text tutorial on how to edit the apk file and access the Exagear source code.

**Comment by ewt45** [comment]
what is the content of the new apk?
if you want to extract the exagear apk file itself, it's easy, there are plenty of tutorial on the internet about extracting apk file with java code.
if you want to call system to install a certain new apk, then you can put the new apk into exagear's apk/assets. and search tutorials about access to apk assets with java code.

**Comment by saman-aliveisi** [comment]
thanks bro.
In fact, I want to edit the exager itself. For example, add a new resolution in the resolutions activity. Either add a new button in the activity related to games or add a new activity to exagear. Finally, I have to change the Exagear codes and get a new APK output.

For this purpose, I searched a lot on the internet, but I didn't find anything. I would be grateful if you could help me or send me a tutorial.

**Comment by ewt45** [comment]
that would be hard.
actually i'm doing this, but in an extra apk rather than exagear itself.
 you need to extract dex from apk, then decode the dex in to smalis, so that you could change the code in smalis.
then encode smalis back into dex, and replace dex in apk.
finally sign the apk with a signature.
what you need to find: tools for decode/encode dex(e.g. apktool), tools for signing apk(e.g. google apksig). you also need to know how to add these tools' as dependencies to your project, and how to use them with code.
if you don't have a project of your own, it seems impossible to finish this task.

moreover, apktool doesn't fully support as android module, so you need to modify its source code to make it work on android

**Comment by saman-aliveisi** [comment]
Thanks for the great answer.
Yes 
I exactly want to do this under the new project and new apk ( in an extra apk rather than exagear itself with a new signature).
please help me for this.

**Comment by ewt45** [comment]
https://github.com/ewt45/EDPatch
this is what it looks like.
the code in repository is not complete, i didn't upload the dependencies.
